cocktails/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='cocktails'),
    # access through view
    path('<int:cocktail_id>', views.cocktail, name='cocktail'),
    path('search', views.search, name='search'),
]

distiller/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('cocktails/', include('cocktails.urls')),
    path('reviews/', include('reviews.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('whiskey', views.whiskey, name='whiskey'),
]

reviews/urls.py
from django.urls import path

from . import views

app_name = 'reviews' 

urlpatterns = [
    path('', views.review, name='review'),
    path('reviews/<int:review_id>', views.review_detail, name='review_detail'),
    path('whiskey', views.whiskey_list, name='whiskey_list'),
    path('whiskey/', views.whiskey_detail, name='whiskey_detail'),
    path('whiskey/<int:whiskey_id>/add_review', views.add_review, name='add_review'),
]

cocktails/models.py
from django.db import models
from datetime import datetime


class Cocktail(models.Model):
    title = models.CharField(max_length=120)
    description = models.CharField(max_length=120)
    instructions = models.TextField(blank=False, null=True)
    ingredient1 = models.CharField(max_length=120, null=True)
    ingredient2 = models.CharField(max_length=120, null=True)
    ingredient3 = models.CharField(max_length=120, null=True)
    ingredient4 = models.CharField(max_length=120, null=True)
    glass = models.CharField(max_length=120, null=True)
    measure1 = models.CharField(max_length=120,  null=True)
    measure2 = models.CharField(max_length=120,  null=True)
    measure3 = models.CharField(max_length=120,  null=True)
    measure4 = models.CharField(max_length=120,  null=True)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/',  height_field=None, width_field=None, max_length=None, null=True)
    photo1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    is_published = models.BooleanField(default=True)
    list_date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.title

pages/models.py
from django.db import models

# Create your models here.

reviews/models.py
from django.db import models
import numpy as np


class Whiskey(models.Model):
    name = models.CharField(max_length=200)

    def average_rating(self):
        all_ratings = map(lambda x: x.rating, self.review_set.all())
        return np.mean(all_ratings)

    '''
    A double underscore prefix causes the Python interpreter to rewrite the attribute name in order to avoid naming conflicts in subclasses.

    Since Python 3.0, all strings are stored as Unicode in an instance of the str type. Encoded strings on the other hand are represented as binary data in the form of instances of the bytes type. Conceptional, str refers to text, whereas bytes refers to data. Use str.encode() to go from str to bytes, and bytes.decode() to go from bytes to str.
    '''

    def __str__(self):
        return self.name


class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    # ForeignKey = Each review is related to a specific whiskey
    whiskey = models.ForeignKey(Whiskey, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published')
    user_name = models.CharField(max_length=100)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=RATING_CHOICES)

utils/models.py
from django.db import models

# Create your models here.

reviews/forms.py
from django.forms import ModelForm, Textarea
from reviews.models import Review


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['user_name', 'rating', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),
        }

cocktails/views.py
from django.shortcuts import render

from . models import Cocktail


def index(request):  
    cocktails = Cocktail.objects.all()

    context = {
        'cocktails': cocktails
    }

    # Bring in info by using a dictionary
    return render(request, 'cocktails/cocktails.html', context)


def cocktail(request):
    return render(request, 'cocktails/cocktail.html')


def search(request):
    return render(request, 'cocktails/search.html')

pages/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return render(request, 'pages/index.html')


def about(request):
    return render(request, 'pages/about.html')


def whiskey(request):
    return render(request, 'pages/whiskey.html')

reviews/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Review, Whiskey
from .forms import ReviewForm
import datetime
from .models import Review, Whiskey

'''
We have defined four different views (one for each of the four different url mappings). 
Each function gets at least a request object parameter, and optionally more parameters as specified in the url mapping. For example, the review_detail function gets also a review_id parameter as we specified in the mapping.
'''


def review(request):
    latest_review_list = Review.objects.order_by('-pub_date')[:9]
    context = {'latest_review_list': latest_review_list}
    return render(request, 'reviews/reviews.html', context)


#  =====================================================
# gets a list of the latest 9 reviews and renders it using `reviews/list.html'.


def review_list(request):
    # ℹ Queries are performed by using the .objects attribute.
    latest_review_list = Review.objects.order_by('-pub_date')[:9]
    context = {'latest_review_list': latest_review_list}
    return render(request, 'reviews/review_list.html', context)


#  =====================================================
# gets a review given its ID and renders it using review_detail.html.

def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'reviews/review_detail.html', {'review': review})


#  =====================================================
# gets all the whiskey sorted by name and passes it to Whiskey_list.html to be rendered.

def whiskey_list(request):
    # ℹ
    whiskey_list = Whiskey.objects.order_by('-name')
    context = {'whiskey_list': whiskey_list}
    return render(request, 'reviews/whiskey_list.html', context)


#  =====================================================
# gets whiskey from DB given its ID and renders it using whiskey_detail.html.

def whiskey_detail(request, whiskey_id):
    whiskey = get_object_or_404(Whiskey, pk=whiskey_id)
    return render(request, 'reviews/whiskey_detail.html', {'whiskey': whiskey, 'form': form})


'''
The add_review function is in charge of validating the form and creating the new review instance. The first thing it does is to use the request url whiskey ID to look for the whiskey we are going to add the review to. It will redirect the view to a 404 page if it doesn't find it. Otherwise, it will create a ReviewForm instance from the request POST data).
'''


def add_review(request, wine_id):
    whiskey = get_object_or_404(whiskey, pk=whiskey_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        rating = form.cleaned_data['rating']
        comment = form.cleaned_data['comment']
        user_name = form.cleaned_data['user_name']
        review = Review()
        review.whiskey = whiskey
        review.user_name = user_name
        review.rating = rating
        review.comment = comment
        review.pub_date = datetime.datetime.now()
        review.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('reviews:whiskey_detail', args=(whiskey.id,)))

    return render(request, 'reviews/wine_detail.html', {'wine': wine, 'form': form})

utils/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!--==================================================-->
    <!--================ Google Tag Manager =================-->
    <!--==================================================-->
    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start': new Date().getTime(),
                event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s),
                dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src =
                'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-NS2L8WT');

    </script>
    <!--==================================================-->
    <!--============== END Google Tag Manager ===============-->
    <!--==================================================-->

    <!--  Meta Data  -->
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" sizes="96x96" href="../assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="theme-color" content="#FAE596" />

    <title>Online Liquor Emporium</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=1' name='viewport' />
    <meta name="Description" content="Award winning whiskey delivered to your door.">
    <meta name="viewport" content="width=device-width" />

    <!--  Stylesheets  -->
    <link href="{% static './bootstrap3/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static './css/gsdk.css' %}" rel="stylesheet" />
    <link href="{% static './core-css/examples.min.css' %} " rel="stylesheet" />
    <link href="{% static './core-css/gsdk.min.css' %}" rel="stylesheet" />
    <link href="{% static './css/animate.min.css' %}" rel="stylesheet" />
    <link href="{% static './css/gsdk.min.css' %}" rel="stylesheet"/>

    <!--     Fonts and icons     -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Grand+Hotel|Open+Sans:400,300' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abel&display=swap" rel="stylesheet">


    <link href="{% static './css/pe-icon-7-stroke.css' %}" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lobster+Two&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="path/to/pe-icon-7-stroke/css/pe-icon-7-stroke.css">
    <script src="https://kit.fontawesome.com/ff12af2cd8.js" crossorigin="anonymous"></script>

    <!--     Google Adsense     -->
    <script data-ad-client="ca-pub-5394101220893720" async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

    <!-- MANIFEST SPLASH SCREEN
    The web app manifest is a simple JSON file that tells the browser about your web application and how it should behave when 'installed' on the user's mobile device or desktop. -->

    <link rel="manifest" href="{% static './manifest.json' %}">
    <!--    TERMLY -- Cookie Policy   -->
    <script>
        (function () {
            var s = document.createElement('script');
            s.type = 'text/javascript';
            s.async = true;
            s.src = 'https://app.termly.io/embed.min.js';
            s.id = '8cd62f32-acde-45a4-bf8b-57de741c7df4';
            s.setAttribute("data-name", "termly-embed-banner");
            var x = document.getElementsByTagName('script')[0];
            x.parentNode.insertBefore(s, x);
        })();

    </script>
</head>

<body>
    <!-- ------------------------------------------------------------------ -->
    <!--  Google Tag Manager (noscript) -->
    <!-- ------------------------------------------------------------------ -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NS2L8WT" height="0" width="0"
            style="display:none;visibility:hidden"></iframe></noscript>
    <!-- ------------------------------------------------------------------ -->
    <!--  END Google Tag Manager (noscript) -->
    <!-- ------------------------------------------------------------------ -->

    <!-- NavBar -->
    {% include 'partials/_navbar.html' %}
    {% block content %} {% endblock %}
    {% include 'partials/_footer.html' %}
    
    <!--###############################-->
    <!--##########  Styles ##############-->
    <!--###############################-->

    <!-- wow.js -->
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js">

    <!--  jQuery and Bootstrap core files    -->
    <script src="{% static './js/jquery.js' %}" type="text/javascript"></script>
    <script src="{% static './js/jquery-ui.custom.min.js' %}" type="text/javascript"></script>
    <script src="{% static './bootstrap3/js/bootstrap.min.js' %}" type="text/javascript"></script>

    <script>
        $(document).ready(function(){
          $('[data-toggle="tooltip"]').tooltip();
        });
        </script>

    <!--  Plugins -->
    <script src="{% static './js/gsdk-checkbox.js' %}"></script>
    <script src="{% static './js/gsdk-morphing.js' %}"></script>
    <script src="{% static './js/gsdk-radio.js' %}"></script>
    <script src="{% static './js/gsdk-bootstrapswitch.js' %}"></script>
    <script src="{% static './js/bootstrap-select.js' %}"></script>
    <script src="{% static './js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static './js/chartist.min.js' %}"></script>
    <script src="{% static './js/jquery.tagsinput.js' %}"></script>
    <script src="{% static './js/rating.min.js' %}"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>


    <!--  Core javascript 	 -->
    <script src="{% static './js/get-shit-done.js' %}"></script>

    <script type="text/javascript">
        var big_image;
        $().ready(function () {
            responsive = $(window).width();

            $(window).on('scroll', gsdk.checkScrollForTransparentNavbar);

            if (responsive >= 768) {
                big_image = $('.parallax-image').find('img');

                $(window).on('scroll', function () {
                    parallax();
                });
            }

        });

        var parallax = function () {
            var current_scroll = $(this).scrollTop();

            oVal = ($(window).scrollTop() / 3);
            big_image.css('top', oVal);
        };

    </script>

    <script>
        $(document).ready(function () {
            // Add smooth scrolling to all links
            $("a").on('click', function (event) {

                // Make sure this.hash has a value before overriding default behavior
                if (this.hash !== "") {
                    // Prevent default anchor click behavior
                    event.preventDefault();

                    // Store hash
                    var hash = this.hash;

                    // Using jQuery's animate() method to add smooth page scroll
                    // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area

                    $('html, body').animate({
                        scrollTop: $(hash).offset().top
                    }, 800, function () {

                        // Add hash (#) to URL when done scrolling (default click behavior)
                        window.location.hash = hash;
                    });
                } // End if
            });
        });

    </script>
</body>

</html>

templates/cocktails/cocktail.html
<h1>This is the selected cocktail</h1>

templates/cocktails/cocktails.html
{% extends "base.html" %}
<!-- List of cocktails -->
{% block  content %}
<!-- Breadcrumb -->
<section id="bootstrap-overrides">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'index' %}">
                        <i class="fas fa-home"></i> Home</a>
                </li>
                <li class="breadcrumb-item active"> Browse Cocktails</li>
            </ol>
        </nav>
    </div>
</section>
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h2 class="wow pulse"
                    style="font-family: 'Fredoka One', cursive; color: #E81AD3; text-transform: uppercase;">Rockin'
                    Cocktails</h2>
            </div>
        </div>
    </div>
</section>
<!-- Cocktails -->
<div class="section ">
    <div class="container container-border">
        <div class="row">
            {% if cocktails %}
            {% for cocktail in cocktails %}
            <div class="col-md-6 col-lg-4 mb-4">
                <div class="image">
                    <a href="#">
                        <img src="{{ cocktail.photo_main.url }}" alt="..."  style="width: 100px; height: 100px;"/>
                    </a>
                </div>
                <div class="content">
                    <a href="#">
                        <h4 class="title">{{ cocktail.title }}</h4>
                    </a>
                    <h4>
                    <i class="fas fa-glass-whiskey"><span style="font-family: 'Abel', sans-serif;"> GLASS TYPE</span></i>
                    </h4>
                        <p class="glass">
                            {{ cocktail.glass }}
                        </p>
                    <h4>
                    <i class="fas fa-clipboard-list"><span style="font-family: 'Abel', sans-serif;"> DESCRIPTION</span></i>
                    <p class="description">
                        {{ cocktail.description }}
                    </p>
                    <h4>
                    <i class="fas fa-mortar-pestle"><span style="font-family: 'Abel', sans-serif;">  INGREDIENTS</span></i>
                    </h4>
                    <ul>
                        <li>
                            {{ cocktail.ingredient1 }}
                            {{ cocktail.measure1 }}
                        </li>
                        <li>
                            {{ cocktail.ingredient2 }}
                            {{ cocktail.measure2 }}
                        </li>
                        <li>
                            {{ cocktail.ingredient3 }}
                            {{ cocktail.measure3 }}
                        </li>
                        <li>
                            {{ cocktail.ingredient4 }}
                            {{ cocktail.measure4 }}
                        </li>
                    </ul>
                    <h4>
                        <i class="fas fa-list-ol"><span style="font-family: 'Abel', sans-serif;"> INSTRUCTIONS</span></i>
                    </h4>
                    <p class="instructions">
                       {{ cocktail.instructions }}
                    </p>

                    <div class="footer" style="background-color: transparent;">
                        <span class="price"> € 3,330</span>
                        <button class="btn btn-danger btn-simple btn-hover pull-right" rel="tooltip" title=""
                            data-placement="left" data-original-title="Add to wishlist">
                            <i class="fa fa-heart-o"></i>
                        </button>
                    </div>
                </div>
            </div> <!-- end card -->
            {% endfor %}
            {% else %}
            <div class="col-md-12">
                <p>No cocktails available</p>
            </div>
            {% endif %}
        </div>
    </div> <!-- end row -->
</div>
<div class="section">
    <div class="container container-border">
    </div> <!-- end card -->
</div>
{% endblock  %}

templates/cocktails/search.html
<h1>Search page</h1>

templates/pages/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="wrapper">
    <div class="parallax filter-black">
        <div class="parallax-image">
            <img src="{% static '/img/bourbon-cocktail-on-the-rocks.jpg' %}">
        </div>
        <div class="small-info">
            <h1>About Us</h1>
            <h3>Just a bunch of people who love whiskey.</h3>
        </div>
    </div>

    <div class="section">
           <div class="container">
               <h2 class="quote" style="font-family: 'Great Vibes', cursive;">Whiskey is liquid sunshine - George Bernard Shaw</h2>
               <div class="row">
                   <div class="col-md-6">
                       <p>
                          Tipplehouse is a place for both amateurs and connoisseurs. A place to learn about how whiskey is made, different varieties of whiskey and whiskey culture in general. </p>
                        <p><b>Enjoy and please drink responsibly.</p>
               </div>
           </div>
    </div><!-- section -->
{% endblock  %}

templates/reviews/review_detail.html
{% extends "base.html" %}
<h3>Recent reviews</h3>

{% if whiskey.review_set.all %}
<div>
    {% for review in whiskey.review_set.all %}
    <div>
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this whiskey yet</p>
{% endif %}

<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'reviews:add_review' whiskey.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" />
</form>

templates/reviews/review_list.html
{% extends "base.html" %}
{% block content %}
<h2>Latest reviews</h2>
{% if latest_review_list %}
<div>
    {% for review in latest_review_list %}
    <div>
        <h4><a href="{% url 'reviews:review_detail' review.id %}">
        {{ review.whiskey.name }}
        </a></h4>
        <h6>rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <p>{{ review.comment }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}

{% endblock content %}

templates/reviews/reviews.html
{% extends "base.html" %}
{% block content %}
<h4>Simple Table with Actions</h4>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th class="text-center">#</th>
                <th>BRAND</th>
                <th>Commentator</th>
                <th>Rating</th>
                <th>Comment</th>
                {% if latest_review_list %}
                {% for review in latest_review_list %}
                <a href="{% url 'reviews:review_detail' review.id %}">
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-center">1</td>
                </td>
                <td>{{ review.whiskey.name }}</td>
                <td>{{ review.user_name }}</td>
                <td>rated {{ review.rating }} of 5 <i class="fas fa-star"></i></td>
                <td>{{ review.comment }}</td>
            </tr>
            <tr>
                {% endfor %}
                {% else %}
                <p>No reviews are available.</p>
                {% endif %}
            </div>
        </tbody>
    </table>
<!-- Comments area -->
<div class="separator"></div>
<div class="container" id="comments">
    <div class="tim-title">
        <h3>Comments Area</h3>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="media-area">
                <h3 class="text-center">10 Comments</h3>
                <div class="media">
                      <a class="pull-left" href="#">
                       <div class="avatar">
                            <img class="media-object" src="assets/img/default-avatar.png" alt="..."/>
                       </div>
                      </a>
                      <div class="media-body">
                        <!-- {% if latest_review_list %}
                        <div>
                            {% for review in latest_review_list %}
                            <div>
                                <h4><a href="{% url 'reviews:review_detail' review.id %}">
                                <h3>Brand</h3>
                                {{ review.whiskey.name }}
                                </a></h4>
                                <h6>rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
                                <p>{{ review.comment }}</p>
                            </div>
                            {% endfor %}
                        </div>
                        {% else %}
                        <p>No reviews are available.</p>
                        {% endif %} -->
                        <div class="media-footer">
                            <a href="#" class="btn btn-info btn-simple "> <i class="fa fa-reply"></i> Reply</a>
                            <a href="#" class="btn btn-danger btn-simple pull-right">
                                 <i class="fa fa-heart"></i> 243
                            </a>
                        </div>

                         <div class="media media-post">
                                 <a class="pull-left author" href="#">
                                  <div class="avatar">
                                        <img class="media-object" src="assets/img/default-avatar.png" alt="..."/>
                                  </div>
                              </a>
                              <div class="media-body">
                                    <textarea class="form-control" placeholder="Write a nice reply or go home..." rows="4"></textarea>
                                    <div class="media-footer">
                                         <a href="#" class="btn btn-info btn-fill pull-right">Reply</a>
                                    </div>
                              </div>
                         </div> <!-- end media-post -->
                      </div>
                </div> <!-- end media -->

                <!--  Comment                    -->
                <div class="media">
                  <a class="pull-left" href="#">
                      <div class="avatar">
                            <img class="media-object" src="assets/img/default-avatar.png" alt="..."/>
                      </div>
                  </a>
                  <div class="media-body">

                     <h4 class="media-heading">Drake</h4>
                     <h6 class="pull-right text-muted">Sep 11, 11:54 AM</h6>

                     <p>Hello guys, nice to have you on the platform! There will be a lot of great stuff coming soon. We will keep you posted for the latest news.</p>
                     <p> Don't forget, You're Awesome!</p>

                     <div class="media-footer">
                         <a href="#" class="btn btn-info btn-simple "> <i class="fa fa-reply"></i> Reply</a>
                         <a href="#" class="btn btn-default btn-simple pull-right">
                             <i class="fa fa-heart-o"></i> 23
                         </a>
                     </div>
                     <div class="media">
                          <a class="pull-left" href="#">
                              <div class="avatar">
                                     <img class="media-object" src="assets/img/default-avatar.png" alt="..."/>
                              </div>
                          </a>
                          <div class="media-body">
                                <h4 class="media-heading">Rick Ross</h4>
                                <h6 class="pull-right text-muted">Sep 11, 11:56 AM</h6>

                                <p>Hello guys, nice to have you on the platform! There will be a lot of great stuff coming soon. We will keep you posted for the latest news.</p>
                                <p> Don't forget, You're Awesome!</p>

                                <div class="media-footer">
                                    <a href="#" class="btn btn-info btn-simple "> <i class="fa fa-reply"></i> Reply</a>
                                    <a href="#" class="btn btn-danger btn-simple pull-right">
                                         <i class="fa fa-heart"></i> 43
                                    </a>
                                </div>
                          </div>
                      </div> <!-- end media -->
                  </div>
                </div> <!-- end media -->
                <div class="media">
                      <a class="pull-left" href="#">
                          <div class="avatar">
                                 <img class="media-object" src="assets/img/default-avatar.png" alt="..."/>
                          </div>
                      </a>
                      <div class="media-body">
                            <h4 class="media-heading">Jay Z</h4>
                            <h6 class="pull-right text-muted">Sep 11, 11:57 AM</h6>

                            <p>Hello guys, nice to have you on the platform! There will be a lot of great stuff coming soon. We will keep you posted for the latest news.</p>
                            <p> Don't forget, You're Awesome!</p>

                            <div class="media-footer">
                                <a href="#" class="btn btn-info btn-simple "> <i class="fa fa-reply"></i> Reply</a>
                                <a href="#" class="btn btn-default btn-simple pull-right">
                                       <i class="fa fa-heart-o"></i> 24
                                </a>
                            </div>
                      </div>
                </div> <!-- end media -->
{% endblock content %}

templates/reviews/whiskey_detail.html
{% extends "base.html" %}
<h3>Recent reviews</h3>

{% if whiskey.review_set.all %}
<div>
    {% for review in whiskey.review_set.all %}
    <div>
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this whiskey yet</p>
{% endif %}

<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'reviews:add_review' whiskey.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" />
</form>